// exchange-stat-ng/src/settings-form/settings-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';

import { StoreService } from '../app/store.service';

@Component({
  selector: 'app-settings-form',
  templateUrl: './settings-form.component.html',
  styleUrls: ['./settings-form.component.sass']
})
export class SettingsFormComponent implements OnInit {
  form: FormGroup;
  currencies = [];
  currTitles = [];
  exchIds = [];
  exchTitles = [];
  currIds = [];
  exchangers = [];


  ngOnInit(): void {
    this._store.getCurrencies();
    this._store.currencies.subscribe(res => {
      console.log(res);
      this.currencies = res;
      console.log(this.currencies);
      // tslint:disable-next-line:prefer-for-of
      for (let i = 0; i < this.currencies.length; i++) {
        this.currTitles.push(this.currencies[i].currencyTitle);
        this.currIds.push(this.currencies[i].currencyId);
      }
      console.log(this.currTitles);
    }, err => {
      console.log(err);
    });
    this._store.getExchangers();
    this._store.exchangers.subscribe(res => {
      console.log(res);
      this.exchangers = res;
      // tslint:disable-next-line:prefer-for-of
      for (let i = 0; i < this.exchangers.length; i++) {
        this.exchTitles.push(this.exchangers[i].exchangerTitle);
        this.exchIds.push(this.exchangers[i].exchangerId);
      }
      console.log(this.currTitles);
    }, err => {
      console.log(err);
    });
  }




  // tslint:disable-next-line:variable-name
  constructor(private formBuilder: FormBuilder, private _store: StoreService) {
    this.form = this.formBuilder.group({
      inCurr: ['', Validators.required],
      outCurr: ['', Validators.required],
      exchanger: ['', Validators.required],
      days: [''],
      hours: [''],
      mins: ['']
    });

  }
}

<form [formGroup]="form" (ngSubmit)="submit()">

  <div class="row">
    <div class="col md6">
      <label for="inCurr">Вхідна валюта</label>
      <select class="form-control" formControlName="inCurr" id="inCurr">
        <option *ngFor="let currTitle of currTitles">
          {{currTitle}}
        </option>
      </select>
    </div>
    <div class="col md6">
      <label for="outCurr">Вихідна валюта</label>
      <select class="form-control" formControlName="outCurr" id="outCurr">
        <option *ngFor="let currTitle of currTitles">
          {{currTitle}}
        </option>
      </select>
    </div>
  </div>
  <div class="mt-2">
    <label for="exchanger">Обмінник</label>
    <select class="form-control" formControlName="exchanger" id="exchanger">
      <option *ngFor="let exchTitle of exchTitles">
        {{exchTitle}}
      </option>
    </select>
  </div>
  <div class="row mt-2">
    <div class="col md4">
      <label for="blockTime">Днів</label>
      <input class="form-control" formControlName="days" id="days">
    </div>
    <div class="col md4">
      <label for="blockTime">Годин</label>
      <input class="form-control" formControlName="hours" id="hours">
    </div>
    <div class="col md4">
      <label for="blockTime">Хвилин</label>
      <input class="form-control" formControlName="mins" id="mins">
    </div>
  </div>

  <div class="mt-3">
    <button type="button" class="btn btn-primary float-right">Submit</button></div>
</form>

// exchange-stat-front/src/components/Settings-form.vue


<template>
  <form
    @submit="checkForm"
    method="post">
    <div class="row">
      <div class="input-field col s6">
        <p class="s-label">Вхідна валюта</p>
        <select
          class="browser-default"
          v-model="formData.inCurr">
          <option value="" disabled selected>Вхідна валюта</option>
          <option v-for="currency in currencies" :value="currency" :key="currency.currencyId">{{currency.currencyTitle}}</option>
        </select>
      </div>
      <div class="input-field col s6">
        <p class="s-label">Вихідна валюта</p>
        <select
          class="browser-default"
          v-model="formData.outCurr">
          <option value="" disabled selected>Вихідна валюта</option>
          <option v-for="currency in currencies" :value="currency" :key="currency.currencyId">{{currency.currencyTitle}}</option>
        </select>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <p class="s-label">Обмінник</p>
        <select
          class="browser-default"
          v-model="formData.changer">
          <option value="" disabled selected>Обмінник</option>
          <option v-for="exchanger in exchangers"
            v-bind:value="exchanger"
            v-bind:key="exchanger.exchangerId">
            {{exchanger.exchangerTitle}}
          </option>
        </select>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s4">
        <input
          type="number"
          v-model="formData.days">
        <label for="blockTime">Днів</label>
      </div>
      <div class="input-field col s4">
        <input
          type="number"
          v-model="formData.hours">
        <label for="blockTime">Годин</label>
      </div>
      <div class="input-field col s4">
        <input
          type="number"
          v-model="formData.minutes">
        <label for="blockTime">Хвилин</label>
      </div>
    </div>
    <div class="row">
      <!-- <a href="#!"> -->
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
          <i class="fas fa-arrow-right"></i>
        </button>
      <!-- </a> -->
    </div>
  </form>
  
</template>
<script src="/path/to/vue-router.js"></script>
<script>
import axios from 'axios'

export default {
  name: "SettingsForm",
  methods: {
    checkForm: function(event) {
      event.preventDefault()
      const params = {
        inCurrencyTitle: this.formData.inCurr.currencyTitle,
        inCurrencyId: this.formData.inCurr.currencyId,
        outCurrencyTitle: this.formData.outCurr.currencyTitle,
        outCurrencyId: this.formData.outCurr.currencyId,
        changerTitle: this.formData.changer.exchangerTitle,
        changerId: this.formData.changer.exchangerId,
        hidePeriod: this.formData.days * 86400000 + this.formData.hours * 3600000 + this.formData.minutes * 60000
      }
      axios.post('http://localhost:9000/temp-hide', params).then(response => {
        // eslint-disable-next-line
        // console.log(response)
        router.push('/')
      })
    },
    getCurrencies: function () {
      axios.get('http://localhost:9000/currencies').then(response => {
        // eslint-disable-next-line
        // console.log(response.data)
        if (response.data && response.status === 200) this.currencies = response.data
      })
    },
    getExchangers: function () {
      axios.get('http://localhost:9000/exchangers').then(response => {
        // eslint-disable-next-line
        // console.log(response.data)
        if (response.data && response.status === 200) this.exchangers = response.data
      })
    }
  },
  data: function() {
    return {
      formData: {
        inCurr: {
          currencyId: null,
          currencyTitle: null
        },
        outCurr: {
          currencyId: null,
          currencyTitle: null
        },
        changer: {
          exchangerId: null,
          exchangerTitle: null
        },
        days: 0,
        hours: 0,
        minutes: 0
      },
      exchangers: [],
      currencies: []
    };
  },
  created: function() {
    this.getCurrencies()
    this.getExchangers()
  }
};
</script>

<style>
.s-label {
  color: #9e9e9e
}
</style>
