// exchange-stat-front/src/components/Settings-form.vue


<template>
  <form
    @submit="checkForm"
    method="post">
    <div class="row">
      <div class="input-field col s6">
        <p class="s-label">Вхідна валюта</p>
        <select
          class="browser-default"
          v-model="formData.inCurr">
          <option value="" disabled selected>Вхідна валюта</option>
          <option v-for="currency in currencies" :value="currency" :key="currency.currencyId">{{currency.currencyTitle}}</option>
        </select>
      </div>
      <div class="input-field col s6">
        <p class="s-label">Вихідна валюта</p>
        <select
          class="browser-default"
          v-model="formData.outCurr">
          <option value="" disabled selected>Вихідна валюта</option>
          <option v-for="currency in currencies" :value="currency" :key="currency.currencyId">{{currency.currencyTitle}}</option>
        </select>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <p class="s-label">Обмінник</p>
        <select
          class="browser-default"
          v-model="formData.changer">
          <option value="" disabled selected>Обмінник</option>
          <option v-for="exchanger in exchangers"
            v-bind:value="exchanger"
            v-bind:key="exchanger.exchangerId">
            {{exchanger.exchangerTitle}}
          </option>
        </select>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s4">
        <input
          type="number"
          v-model="formData.days">
        <label for="blockTime">Днів</label>
      </div>
      <div class="input-field col s4">
        <input
          type="number"
          v-model="formData.hours">
        <label for="blockTime">Годин</label>
      </div>
      <div class="input-field col s4">
        <input
          type="number"
          v-model="formData.minutes">
        <label for="blockTime">Хвилин</label>
      </div>
    </div>
    <div class="row">
      <!-- <a href="#!"> -->
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
          <i class="fas fa-arrow-right"></i>
        </button>
      <!-- </a> -->
    </div>
  </form>
  
</template>
<script src="/path/to/vue-router.js"></script>
<script>
import axios from 'axios'

export default {
  name: "SettingsForm",
  methods: {
    checkForm: function(event) {
      event.preventDefault()
      const params = {
        inCurrencyTitle: this.formData.inCurr.currencyTitle,
        inCurrencyId: this.formData.inCurr.currencyId,
        outCurrencyTitle: this.formData.outCurr.currencyTitle,
        outCurrencyId: this.formData.outCurr.currencyId,
        changerTitle: this.formData.changer.exchangerTitle,
        changerId: this.formData.changer.exchangerId,
        hidePeriod: this.formData.days * 86400000 + this.formData.hours * 3600000 + this.formData.minutes * 60000
      }
      axios.post('http://localhost:9000/temp-hide', params).then(response => {
        // eslint-disable-next-line
        // console.log(response)
        router.push('/')
      })
    },
    getCurrencies: function () {
      axios.get('http://localhost:9000/currencies').then(response => {
        // eslint-disable-next-line
        // console.log(response.data)
        if (response.data && response.status === 200) this.currencies = response.data
      })
    },
    getExchangers: function () {
      axios.get('http://localhost:9000/exchangers').then(response => {
        // eslint-disable-next-line
        // console.log(response.data)
        if (response.data && response.status === 200) this.exchangers = response.data
      })
    }
  },
  data: function() {
    return {
      formData: {
        inCurr: {
          currencyId: null,
          currencyTitle: null
        },
        outCurr: {
          currencyId: null,
          currencyTitle: null
        },
        changer: {
          exchangerId: null,
          exchangerTitle: null
        },
        days: 0,
        hours: 0,
        minutes: 0
      },
      exchangers: [],
      currencies: []
    };
  },
  created: function() {
    this.getCurrencies()
    this.getExchangers()
  }
};
</script>

<style>
.s-label {
  color: #9e9e9e
}
</style>

// exchange-stat-ng/src/app/settings-form/settings-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';

import { StoreService } from '../store.service';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-settings-form',
  templateUrl: './settings-form.component.html',
  styleUrls: ['./settings-form.component.sass']
})
export class SettingsFormComponent implements OnInit {
  form: FormGroup;
  currencies = [];
  exchangers = [];

  ngOnInit(): void {
    this._store.getCurrencies();
    this._store.currencies.subscribe(res => {
      console.log(res);
      this.currencies = [{changerTitle: '', changerId: null}, ...res];
    }, err => {
      console.log(err);
    });
    this._store.getExchangers();
    this._store.exchangers.subscribe(res => {
      this.exchangers = [{currencyTitle: '', currencyId: null}, ...res];
    }, err => {
      console.log(err);
    });
  }

  // tslint:disable-next-line:variable-name
  constructor(private formBuilder: FormBuilder, private _store: StoreService, private http: HttpClient) {
    this.form = this.formBuilder.group({
      inCurr: [''],
      outCurr: [''],
      exchanger: [''],
      days: [''],
      hours: [''],
      mins: ['']
    });

  }

  submit() {
    const { value } = this.form;
    if (!value.exchanger && !value.inCurr && !value.outCurr) {
      this._store.showNotification.next({severity: 'error', summary: 'Warning message', detail: `Відбулась помилка.`});
    } else {
      const params = {
        inCurrencyId: value.inCurr || null,
        outCurrencyId: value.outCurr || null,
        changerId: value.exchanger || null,
        hidePeriod: (value.days || 0) * 86400000 + (value.hours || 0) * 3600000 + (value.mins || 0) * 60000
      }
      this.http.post('http://localhost:9000/temp-hide', params).toPromise().then((response: any) => {
        if (response.message === 'success') {
          this._store.showNotification.next({severity: 'success', summary: 'Success', detail: 'Налаштування збережені'});
          this.form.reset();
        } else {
          this._store.showNotification.next({severity: 'error', summary: 'Warning message', detail: `Відбулась помилка. ${response.message}`});
        }
      });
    }
  }
}

<form [formGroup]="form" (ngSubmit)="submit()">

  <div class="row">
    <div class="col md6">
      <label for="inCurr">Вхідна валюта</label>
      <select class="form-control" formControlName="inCurr">
        <option *ngFor="let currency of currencies" [value]="currency.currencyId">
          {{currency.currencyTitle}}
        </option>
      </select>
    </div>
    <div class="col md6">
      <label for="outCurr">Вихідна валюта</label>
      <select class="form-control" formControlName="outCurr">
        <option *ngFor="let currency of currencies" [value]="currency.currencyId">
          {{currency.currencyTitle}}
        </option>
      </select>
    </div>
  </div>
  <div class="mt-2">
    <label for="exchanger">Обмінник</label>
    <select class="form-control" formControlName="exchanger">
      <option *ngFor="let exchanger of exchangers" [value]="exchanger.exchangerId">
        {{exchanger.exchangerTitle}}
      </option>
    </select>
  </div>
  <div class="row mt-2">
    <div class="col md4">
      <label for="blockTime">Днів</label>
      <input class="form-control" formControlName="days">
    </div>
    <div class="col md4">
      <label for="blockTime">Годин</label>
      <input class="form-control" formControlName="hours">
    </div>
    <div class="col md4">
      <label for="blockTime">Хвилин</label>
      <input class="form-control" formControlName="mins">
    </div>
  </div>

  <div class="mt-3">
    <button type="submit" class="btn btn-primary float-right" [disabled]="!form.value.inCurr && !form.value.outCurr && !form.value.exchanger">Submit</button>
  </div>
</form>
