// exchange-stat-front/src/components/CustomChain.vue
<template>
<div>
  <form
    @submit="sendForm"
    method="post">
      <h2>Редактор ланцюжків</h2>
    <div class="row">
      <div class="container">
      <div class="input-field col s4">
        <p class="s-label">Перший крок</p>
        <select class="browser-default" v-model="formData.firstStep">
          <option value="" disabled selected>Перший крок</option>
          <option v-for="currency in currencies" :value="currency" :key="currency.currencyId">{{currency.currencyTitle}}</option>
        </select>
      </div>
      </div>
      <div class="container">
      <div class="input-field col s4">
        <p class="s-label">Другий крок</p>
        <select class="browser-default" v-model="formData.secondStep">
          <option value="" disabled selected>Другий крок</option>
          <option v-for="currency in currencies" :value="currency" :key="currency.currencyId">{{currency.currencyTitle}}</option>
        </select>
      </div>
      </div>
      <div class="container">
      <div class="input-field col s4">
        <p class="s-label">Третій крок</p>
        <select class="browser-default" v-model="formData.thirdStep">
          <option value="" >Третій крок</option>
          <option v-for="currency in currencies" :value="currency" :key="currency.currencyId">{{currency.currencyTitle}}</option>
        </select>
      </div>
      </div>
    </div>
    <div class="container">
      <div class="input-field col s6">
        <input id="first_name" type="number" class="validate" placeholder="Min Balance" v-model="formData.minBalance">
        <label for="first_name">Min Balance $</label>
      </div>
    </div>
    <div class="row">
      <button type="submit" v-bind:disabled="!formData.secondStep.currencyId && !formData.thirdStep.currencyId || !formData.firstStep.currencyId || !formData.minBalance" 
      class="submit-btn btn waves-effect waves-light" >Submit
        <i class="fas fa-arrow-right"></i>
      </button>
    </div>
  </form>
    <vue-good-table
      mode="remote"
      class="bc-table"
      :columns="columns"
      :rows="rows"
      :sort-options="{
        enabled: false
      }"
      />
  </div>
</template>

<script>
import helper from '../helper.js';
import axios from 'axios'
export default {
  name: "CustomChain",
  methods: {
    sendForm: function(event) {
      event.preventDefault()
      if (!this.formData.firstStep.currencyId && !this.formData.secondStep.currencyId && !this.formData.thirdStep.currencyId) {
        this.error = true
      } else {
        const data = {
          firstStepTitle: this.formData.firstStep.currencyTitle,
          firstStepId: this.formData.firstStep.currencyId,
          secondStepTitle: this.formData.secondStep.currencyTitle,
          secondStepId: this.formData.secondStep.currencyId,
          thirdStepTitle: this.formData.thirdStep.currencyTitle,
          thirdStepId: this.formData.thirdStep.currencyId,
          minBalance: this.formData.minBalance
        }
        var chain = [data.firstStepId, data.secondStepId, data.thirdStepId]
        if(data.thirdStepId === undefined){
          chain.pop()
        }
        console.log(chain)
        axios.post('http://localhost:9000/custom-chain', {chain: chain, amount: data.minBalance}).then(response => {
          console.log(response)
          if (response.status === 200) {
            
        console.log(response)

        this.currentDataArr = response.data
        this.rows = response.data.map((element, i) => {

          if (this.notif && element) document.getElementById('aud').play()
          const toDolIndex = element.length - 3
          return {
            gain: helper.calcChainProfit(element, element[element.length - 2]),
            chain: helper.getChainCol(element, toDolIndex, i),
            score: element[element.length - 2] / 100,
            age: this.rows.length ? helper.getAgeOfChain(helper.genId(element)) : 0,
            links: '<i class="fas fa-arrow-right" style="color: #039be5"></i>',
            id: helper.genId(element)
          }
        })
        
        if (response.data.length) {
          this.notif = false
        } else {
          this.rows = []
          this.notif = true
        }
        this.rowsCopy = this.rows
          }else if(response.status === 400) {
            alert('Неможливо знайти ланцюжок')
          }
        })
      }
    },
  getCurrencies: function() {
      axios.get('http://localhost:9000/currencies').then(response => {
        if (response.data && response.status === 200) this.currencies = response.data
      })
    }
  },
  data: function() {
    return {
      formData: {
        firstStep: {
          currencyId: undefined,
          currencyTitle: undefined
        },
        secondStep: {
          currencyId: undefined,
          currencyTitle: undefined
        },
        thirdStep: {
          currencyId: undefined,
          currencyTitle: undefined
        },
        minBalance: null
      },
      error: false,
      currencies: [],
      showSettings: false,
      notif: false,
      chainSubscriptions: '',
      maxChainProfits: [],
      currentDataArr: null,
      columns: [
        {
          label: 'Max Profit',
          field: 'gain',
          html: true,
          globalSearchDisabled: true,
          width: '125px'
        },
        {
          label: 'Ланцюжки',
          field: 'chain',
          type: 'string',
          html: true,
          globalSearchDisabled: false
        },
        {
          label: '%',
          field: 'score',
          type: 'percentage',
          globalSearchDisabled: true
        },
        {
          label: 'Час с',
          field: 'age',
          tdClass: 'age',
          globalSearchDisabled: true
        },
        {
          label: '',
          field: 'links',
          html: true
        }
      ],
      rows: [],
      rowsCopy: []
    };
  },
  created: function() {
    this.getCurrencies()
  }
};
</script>

<style>
h2 {
  text-align: center;
}
.submit-btn {
  margin: 0 auto;
  display: block;
}
</style>

// exchange-stat-ng/src/app/custom-chain/custom-chain.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { StoreService } from '../store.service';
import { Subscription } from 'rxjs';
import { ChainService } from '../main/chain.service';

@Component({
  selector: 'app-custom-chain',
  templateUrl: './custom-chain.component.html',
  styleUrls: ['./custom-chain.component.sass']
})
export class CustomChainComponent implements OnInit {
  cols: any[];
  form: FormGroup;
  currencies = [];
  currSubscription: Subscription;
  chainSubscription: Subscription;
  chains = [];
  // tslint:disable-next-line:variable-name
  constructor(private _chainService: ChainService, private formBuilder: FormBuilder, private _store: StoreService) {
    this.form = this.formBuilder.group({
      firstStep: ['', Validators.required],
      secondStep: [null],
      thirdStep: [''],
      minBalance: ['', Validators.required]
    });
  }

  ngOnInit() {
    this._store.getCurrencies();
    this.currSubscription = this._store.currencies.subscribe(res => {
      console.log(res);
      this.currencies = res;
    }, err => console.log(err));
    this.chainSubscription = this._store.customChain.subscribe(res => {
      const { chain, otherRates } = res;
      this.buildTable(chain, otherRates);
    });
    this.cols = [
      { field: 'gain', header: 'Max Profit' },
      { field: 'chain', header: 'Ланцюжки' },
      { field: 'score', header: '%' },
      { field: 'age', header: 'Час с' },
      { field: 'links', header: '=>' }
    ];
  }

  buildTable(data: any[], otherRates?: any[]) {

    this.chains = data.sort((a, b) => a.length - b.length).map((chainData, i) => {
      const [dollarRate, profit, isSubs] = chainData.splice(chainData.length - 3, 3);
      const generatedId = this._chainService.generateId(chainData);
      return {
        gain: this._chainService.calcChainProfit(chainData, profit),
        chain: {chainData, dollarRate, otherRates},
        score: `${profit.toFixed(2)} %`,
        age: this.chains.length ?
          this._chainService.getAgeOfChain(generatedId, this.chains) : 0,
        options: ' ',
        links: null,
        id: generatedId
      };
    });
  }

  submit() {
    const { firstStep, secondStep, thirdStep, minBalance } = this.form.value;
    const chain = [firstStep, secondStep, thirdStep];
    if (!chain[2]) chain.pop();
    const query = {
      chain: ["120", "121", "142"],
      amount: minBalance || '',
      isGoldMiddle: !secondStep
    };
    console.log(query);
    this._store.getCustomChain(query);
  }

  ngOnDestroy(): void {
    this.currSubscription.unsubscribe();
    this.chainSubscription.unsubscribe();
  }
}


  <a routerLink="/main"><i class="pi pi-arrow-left"></i>Back</a>

  <form [formGroup]="form" (ngSubmit)="submit()">

    <div class="row">
      <div class="col-lg">
        <label for="firstStep">Перший крок</label>
        <select class="form-control" formControlName="firstStep" id="firstStep">
          <option value="" disabled selected>Select currency</option>
          <option *ngFor="let curr of currencies" [value]="curr.currencyId">
            {{curr.currencyTitle}}
          </option>
        </select>
      </div>
      <div class="col-lg">
        <label for="secondStep">Другий крок</label>
        <select class="form-control" formControlName="secondStep" id="secondStep">
          <option value="null" selected>Select currency</option>
          <option *ngFor="let curr of currencies" [value]="curr.currencyId">
            {{curr.currencyTitle}}
          </option>
        </select>
      </div>
      <div class="col-lg">
        <label for="thirdStep">Третій крок</label>
        <select class="form-control" formControlName="thirdStep" id="thirdStep">
          <option value="" selected>Select currency</option>
          <option *ngFor="let curr of currencies" [value]="curr.currencyId">
            {{curr.currencyTitle}}
          </option>
        </select>
      </div>
    </div>
    <div class="row">
      <div class="col-md">
        <label for="minBalance">Minimal Balance $</label>
        <input type="number" class="form-control" formControlName="minBalance" id="minBalance"
          placeholder="Minimal Balance">
      </div>
    </div>

      <button type="submit" class="btn btn-primary col-md-1 mt-3 mb-3" >Submit</button>
      <!-- [disabled]="!form.valid" -->
  </form>

  <p-table [columns]="cols" [value]="chains" rowIndex dataKey="{{rowIndex}}" [autoLayout]="true">  
      <ng-template pTemplate="header" let-columns let-rowData>
        <tr>
          <th *ngFor="let col of columns" [style.width.px]="col.field === 'chain' ? '800' : ''" [pSortableColumn]="col.field">
            {{col.header}}
            <p-sortIcon [field]="col.field" ariaLabel="Activate to sort" ariaLabelDesc="Activate to sort in descending order" ariaLabelAsc="Activate to sort in ascending order"></p-sortIcon>
          </th>
        </tr>
      </ng-template>
      <ng-template pTemplate="body" let-rowData let-rowIndex="rowIndex" let-columns="columns">
        <tr [pSelectableRow]="rowData">
          <td>
            {{rowData.gain}}
          </td>
          <td>
            <app-chain-col [chain]="rowData?.chain.chainData" [dollarRate]="rowData?.chain.dollarRate" [otherRates]="rowData?.chain.otherRates"></app-chain-col>
          </td>
          <td style="width: 80px">
            {{rowData.score}}
          </td>
          <td  style="width: 70px">
            {{rowData.age}}
          </td>
          <td>
            {{rowData.links}}
            <button pButton icon="pi pi-angle-right" (click)="openAllLinks(rowIndex)" type="button"></button>
          </td>
        </tr>
      </ng-template>
    </p-table>
